#!/usr/bin/env zsh

# txp-docs - Documentation helper for txp
#
# Modes:
#   txp-docs --oneline <command-string>   One-line synopsis (for fzf header)
#   txp-docs <command_string>             Full man page excerpt (for Ctrl-D)

setopt err_exit no_unset pipe_fail

ONELINE=0
if [[ ${1:-} == "--oneline" ]]; then
    ONELINE=1
    shift
fi

CMD=${1:-}
DEFAULT_HEADER="  Ctrl-D: docs   Ctrl-Y: copy   Ctrl-R: toggle layout"

if [[ -z $CMD ]]; then
    (( ONELINE )) && print $DEFAULT_HEADER || print "No command specified."
    exit 0
fi

# Extract first command from a pipeline
local first_cmd=${CMD%%|*}
first_cmd=${first_cmd##[[:space:]]#}
first_cmd=${first_cmd%% *}

if [[ -z $first_cmd ]]; then
    (( ONELINE )) && print $DEFAULT_HEADER
    exit 0
fi

# --- One-liner synopses ---

typeset -A synopses=(
    awk      "awk - pattern scanning and processing: awk [-F fs] [-v var=val] 'program' [file ...]"
    cat      "cat - concatenate and print files: cat [-nbE] [file ...]"
    col      "col - filter reverse line feeds from input: col [-bfhx] [-l num]"
    colrm    "colrm - remove columns from a file: colrm [start [stop]]"
    column   "column - columnate lists: column [-t] [-s sep] [file ...]"
    comm     "comm - compare two sorted files line by line: comm [-123] file1 file2"
    csplit   "csplit - split a file into sections determined by context lines: csplit [options] file patterns"
    cut      "cut - remove sections from each line of files: cut [-bcf] [-d delim] [file ...]"
    expand   "expand - convert tabs to spaces: expand [-t tabstop] [file ...]"
    fmt      "fmt - simple optimal text formatter: fmt [-w width] [file ...]"
    fold     "fold - wrap each input line to fit in specified width: fold [-bs] [-w width] [file ...]"
    grep     "grep - print lines matching a pattern: grep [-ivnE] pattern [file ...]"
    head     "head - output the first part of files: head [-n lines] [file ...]"
    join     "join - relational database operator: join [-1 field] [-2 field] [-t char] file1 file2"
    jq       "jq - command-line JSON processor: jq [options] 'filter' [file ...]"
    look     "look - display lines beginning with a given string: look [-dff] string [file]"
    nl       "nl - number lines of files: nl [-ba] [-s sep] [file ...]"
    od       "od - dump files in octal and other formats: od [-abcdfhilovx] [file]"
    paste    "paste - merge lines of files: paste [-d delim] [-s] [file ...]"
    pr       "pr - convert text files for printing: pr [+page] [-column] [-at] [file ...]"
    rev      "rev - reverse lines characterwise: rev [file ...]"
    sed      "sed - stream editor for filtering/transforming text: sed [-Ene] 'script' [file ...]"
    sort     "sort - sort lines of text files: sort [-nrhut] [-k key] [file ...]"
    split    "split - split a file into pieces: split [-l line_count] [-b bytes] [file [prefix]]"
    strings  "strings - print the strings of printable characters in files: strings [-afo] [file ...]"
    tail     "tail - output the last part of files: tail [-n lines] [-f] [file ...]"
    tee      "tee - read from standard input and write to standard output and files: tee [-a] [file ...]"
    tr       "tr - translate or delete characters: tr [-cdst] set1 [set2]"
    uniq     "uniq - report or omit repeated lines: uniq [-cdu] [file [output]]"
    wc       "wc - print newline, word, and byte counts: wc [-clmw] [file ...]"
    xargs    "xargs - build and execute command lines from standard input: xargs [-n num] [-I str] [command]"
)

if (( ONELINE )); then
    if (( ${+synopses[$first_cmd]} )); then
        print "  $synopses[$first_cmd]"
    else
        print "  $first_cmd - Ctrl-D: docs   Ctrl-Y: copy    Ctrl-R: toggle layout"
    fi
    exit 0
fi

# --- Full documentation mode ---

print "ONELINE value is $ONELINE"
print "=== $first_cmd ==="
print ""

if man $first_cmd 2>/dev/null | col -bx | head -120; then
    :
elif $first_cmd --help 2>&1 | head -60; then
    :
elif (( ${+synopses[$first_cmd]} )); then
    print $synopses[$first_cmd]
else
    print "No documentation found for '$first_cmd'"
fi
